### ISSUE TITLE
Try the "Squircle"

### ISSUE THREAD

**Issue by Byloth** [Byloth/clay-vue#1]
```css
.squircle {
  clip-path: shape(
    from 0% 50%, 
    curve by 50% -50% with 0% -45% / 5% -50%, 
    smooth by 50% 50% with 50% 5%, 
    smooth by -50% 50% with -5% 50%, 
    smooth by -50% -50% with -50% -5%
  );
}
```

Here's an example: https://codepen.io/chriscoyier/pen/gbbBOXz
